version: '2.0'

services:
  s3:
    image: minio/minio
    restart: on-failure
    ports:
       - 9000:9000
       - 9090:9090
    volumes:
      - s3:/data
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=12345678
      - MINIO_ACCESS_KEY=minioadmin
    command: server --console-address :9090 --address :9000 /data
  web:
    build: ./electronic_elder
    volumes:
      - ./electronic_elder/:/usr/src/app/
      - static_volume:/usr/src/app/static
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - s3
volumes:
  postgres_data:
  static_volume:
  media_volume:
  redisdata:
  s3: